### ISSUE TITLE
failed running react/redux boilerplate.

### ISSUE THREAD

**Issue by thecodingwhale** [rstacruz/frontend-starter-kit#1]
Hi Rico,

Thanks for creating this frontend stater kit!

Anyway I'm trying to use the react/redux boilerplate but after running the second command:
`$ curl -sSL https://raw.githubusercontent.com/rstacruz/frontend-starter-kit/master/_extras/react/INSTALL.sh | bash`

I get these following errors:

```
tar: Pattern matching characters used in file names
tar: Use --wildcards to enable pattern matching, or --no-wildcards to suppress this warning
tar: */_extras/react: Not found in archive
tar: Exiting with failure status due to previous errors
frontend-starter-kit@1.0.0 /home/aldrenterante/www/cv
├── babel-preset-react@6.16.0 
├── build-reducer@1.2.0 
├── react@15.3.1 
├── react-dom@15.3.1 
├── react-redux@4.4.5 
├── redux@3.6.0 
└── redux-thunk@2.1.0 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN frontend-starter-kit@1.0.0 No repository field.
bash: line 32: warning: here-document at line 19 delimited by end-of-file (wanted `EOF')
fs.js:982
  return binding.lstat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, lstat '/proc/20871/fd/pipe:[499584]'
    at Error (native)
    at Object.fs.lstatSync (fs.js:982:18)
    at Object.realpathSync (fs.js:1647:19)
    at Function.Module._findPath (module.js:167:25)
    at Function.Module._resolveFilename (module.js:453:25)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

I'm using 14.04 ubuntu and NVM (nvm use v6.5) for this one while playing this one.

Thanks,

**Comment by rstacruz** [comment]
Ouch, thanks, if you got some insight on whats going on here lemme know :)

**Comment by rstacruz** [comment]
Worked fine on OSX, but it seems Linux needs `--wildcards` on tar. fixed, thanks for your help!

**Comment by thecodingwhale** [comment]
sorry for the reply! thanks also for fixing the issue!
